return {}
-- return {
-- 	"akinsho/bufferline.nvim",
-- 	version = "*",
-- 	dependencies = "nvim-tree/nvim-web-devicons",
-- 	config = function()
-- 		require("bufferline").setup({
-- 			options = {
-- 				mode = "buffers",
-- 				diagnostics = "nvim_lsp",
-- 				diagnostics_indicator = function(count, level, diagnostics_dict, context)
-- 					local icon = level:match("error") and " " or " "
-- 					return " " .. icon .. count
-- 				end,
-- 				offsets = {
-- 					{
-- 						filetype = "neo-tree",
-- 						text = "File Explorer",
-- 						text_align = "center",
-- 						separator = true,
-- 					},
-- 				},
-- 				separator_style = "thick",
-- 				indicator = {
-- 					-- icon = '▎',
-- 					style = 'icon',
-- 					-- style = "underline",
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
